package classes;

import java.util.ArrayList;

public class LandProvinces {
	public static ArrayList<Province> landProvinces;
	//England
	Province Cly;
	Province Edi;
	Province Lvp;
	Province Yor;
	Province Wal;
	Province Lon;
	//France
	Province Bre;
	Province Pic;
	Province Par;
	Province Bur;
	Province Gas;
	Province Mar;
	//Italy
	Province Pie;
	Province Ven;
	Province Tus;
	Province Rom;
	Province Apu;
	Province Nap;
	//Austria
	Province Tyr;
	Province Boh;
	Province Bud;
	Province Vie;
	Province Gal;
	Province Tri;
	//Ottoman Empire
	Province Con;
	Province Ank;
	Province Arm;
	Province Smy;
	Province Syr;
	//Russia
	Province Fin;
	Province Stp;
	Province Liv;
	Province Mos;
	Province Sev;
	Province War;
	Province Ukr;
	//Germany
	Province Kie;
	Province Ber;
	Province Ruh;
	Province Mun;
	Province Pru;
	Province Sil;
	//Neutral
	Province Spa;
	Province Por;
	Province Tun;
	Province Naf;
	Province Nwy;
	Province Bel;
	Province Hol;
	Province Swe;
	Province Den;
	Province Rum;
	Province Ser;
	Province Bul;
	Province Alb;
	Province Gre;
	public LandProvinces() {
		landProvinces = new ArrayList<Province>();
		Cly = new Province(true,"Cly");
		landProvinces.add(Cly);
		Edi = new Province(true,"Edi");
		landProvinces.add(Edi);
		Lvp = new Province(true,"Lvp");
		landProvinces.add(Lvp);
		Yor = new Province(true,"Yor");
		landProvinces.add(Yor);
		Wal = new Province(true,"Wal");
		landProvinces.add(Wal);
		Lon = new Province(true,"Lon");
		landProvinces.add(Lon);
		Bre = new Province(true,"Bre");
		landProvinces.add(Bre);
		Pic = new Province(true,"Pic");
		landProvinces.add(Pic);
		Par = new Province(true,"Par");
		landProvinces.add(Par);
		Bur = new Province(true,"Bur");
		landProvinces.add(Bur);
		Gas = new Province(true,"Gas");
		landProvinces.add(Gas);
		Mar = new Province(true,"Mar");
		landProvinces.add(Mar);
		Pie = new Province(true,"Pie");
		landProvinces.add(Pie);
		Ven = new Province(true,"Ven");
		landProvinces.add(Ven);
		Tus = new Province(true,"Tus");
		landProvinces.add(Tus);
		Rom = new Province(true,"Rom");
		landProvinces.add(Rom);
		Apu = new Province(true,"Apu");
		landProvinces.add(Apu);
		Nap = new Province(true,"Nap");
		landProvinces.add(Nap);
		Tyr = new Province(true,"Tyr");
		landProvinces.add(Tyr);
		Boh = new Province(true,"Boh");
		landProvinces.add(Boh);
		Bud = new Province(true,"Bud");
		landProvinces.add(Bud);
		Vie = new Province(true,"Vie");
		landProvinces.add(Vie);
		Gal = new Province(true,"Gal");
		landProvinces.add(Gal);
		Tri = new Province(true,"Tri");
		landProvinces.add(Tri);
		Con = new Province(true,"Con");
		landProvinces.add(Con);
		Ank = new Province(true,"Ank");
		landProvinces.add(Ank);
		Arm = new Province(true,"Arm");
		landProvinces.add(Arm);
		Smy = new Province(true,"Smy");
		landProvinces.add(Smy);
		Syr = new Province(true,"Syr");
		landProvinces.add(Syr);
		Fin = new Province(true,"Fin");
		landProvinces.add(Fin);
		Stp = new Province(true,"Stp");
		landProvinces.add(Stp);
		Liv = new Province(true,"Liv");
		landProvinces.add(Liv);
		Mos = new Province(true,"Mos");
		landProvinces.add(Mos);
		Sev = new Province(true,"Sev");
		landProvinces.add(Sev);
		War = new Province(true,"War");
		landProvinces.add(War);
		Ukr = new Province(true,"Ukr");
		landProvinces.add(Ukr);
		Kie = new Province(true,"Kie");
		landProvinces.add(Kie);
		Ber = new Province(true,"Ber");
		landProvinces.add(Ber);
		Ruh = new Province(true,"Ruh");
		landProvinces.add(Ruh);
		Mun = new Province(true,"Mun");
		landProvinces.add(Mun);
		Pru = new Province(true,"Pru");
		landProvinces.add(Pru);
		Sil = new Province(true,"Sil");
		landProvinces.add(Sil);
		Spa = new Province(true,"Spa");
		landProvinces.add(Spa);
		Por = new Province(true,"Por");
		landProvinces.add(Por);
		Tun = new Province(true,"Tun");
		landProvinces.add(Tun);
		Naf = new Province(true,"Naf");
		landProvinces.add(Naf);
		Nwy = new Province(true,"Nwy");
		landProvinces.add(Nwy);
		Bel = new Province(true,"Bel");
		landProvinces.add(Bel);
		Hol = new Province(true,"Hol");
		landProvinces.add(Hol);
		Swe = new Province(true,"Swe");
		landProvinces.add(Swe);
		Den = new Province(true,"Den");
		landProvinces.add(Den);
		Rum = new Province(true,"Rum");
		landProvinces.add(Rum);
		Ser = new Province(true,"Ser");
		landProvinces.add(Ser);
		Bul = new Province(true,"Bul");
		landProvinces.add(Bul);
		Alb = new Province(true,"Alb");
		landProvinces.add(Alb);
		Gre = new Province(true,"Gre");
		landProvinces.add(Gre);
	}
}
